environment: test
spring:
  config:
    activate:
      on-profile: test
name: test-YML
server:
  port: 4000
varTree:
  envName: "Test"
enabled: true

---
environment: prod
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 5000
varTree:
  envName: "Prod"
enabled: true